<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['contents']=array (
  'id' => '2',
  'name' => 'contents',
  'description' => '内容管理',
  'perpage' => '20',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'fields' => 
  array (
    3 => 
    array (
      'id' => '3',
      'name' => 'title',
      'description' => '文章标题',
      'model' => '2',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    4 => 
    array (
      'id' => '4',
      'name' => 'category',
      'description' => '所属导航',
      'model' => '2',
      'type' => 'select_from_model',
      'length' => '0',
      'values' => 'category|category_name',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    5 => 
    array (
      'id' => '5',
      'name' => 'addtime',
      'description' => '发布时间',
      'model' => '2',
      'type' => 'datetime',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    6 => 
    array (
      'id' => '6',
      'name' => 'focus',
      'description' => '焦点图',
      'model' => '2',
      'type' => 'file',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '3',
      'editable' => '1',
    ),
    7 => 
    array (
      'id' => '7',
      'name' => 'contents',
      'description' => '内容',
      'model' => '2',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '4',
      'editable' => '1',
    ),
    8 => 
    array (
      'id' => '8',
      'name' => 'ontop',
      'description' => '排序',
      'model' => '2',
      'type' => 'int',
      'length' => '0',
      'values' => '0',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '5',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '3',
    1 => '4',
    2 => '5',
  ),
  'searchable' => 
  array (
    0 => '3',
    1 => '4',
    2 => '5',
  ),
);