<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['links']=array (
  'id' => '3',
  'name' => 'links',
  'description' => '友情链接',
  'perpage' => '20',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'fields' => 
  array (
    9 => 
    array (
      'id' => '9',
      'name' => 'links_category',
      'description' => '所属链接',
      'model' => '3',
      'type' => 'select_from_model',
      'length' => '0',
      'values' => 'links_category|category_name',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    10 => 
    array (
      'id' => '10',
      'name' => 'link_name',
      'description' => '链接名称',
      'model' => '3',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    11 => 
    array (
      'id' => '11',
      'name' => 'link_url',
      'description' => '链接名称',
      'model' => '3',
      'type' => 'input',
      'length' => '0',
      'values' => '#',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    12 => 
    array (
      'id' => '12',
      'name' => 'ispic',
      'description' => '是否图片',
      'model' => '3',
      'type' => 'radio',
      'length' => '0',
      'values' => 
      array (
        0 => '否',
        1 => '是',
      ),
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    13 => 
    array (
      'id' => '13',
      'name' => 'link_pic',
      'description' => '链接图片',
      'model' => '3',
      'type' => 'file',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '4',
      'editable' => '1',
    ),
    14 => 
    array (
      'id' => '14',
      'name' => 'ontop',
      'description' => '排序',
      'model' => '3',
      'type' => 'int',
      'length' => '0',
      'values' => '0',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '9',
    1 => '10',
    2 => '11',
    3 => '12',
    4 => '14',
  ),
  'searchable' => 
  array (
    0 => '9',
    1 => '14',
  ),
);