<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['models']['videos']=array (
  'id' => '5',
  'name' => 'videos',
  'description' => '视频',
  'perpage' => '20',
  'hasattach' => '1',
  'built_in' => '0',
  'thumb_preferences' => '{"enabled":[],"default":"original"}',
  'fields' => 
  array (
    18 => 
    array (
      'id' => '18',
      'name' => 'title',
      'description' => '视频标题',
      'model' => '5',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    19 => 
    array (
      'id' => '19',
      'name' => 'videos_category',
      'description' => '视频类',
      'model' => '5',
      'type' => 'select_from_model',
      'length' => '0',
      'values' => 'videos_category|category_name',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    20 => 
    array (
      'id' => '20',
      'name' => 'addtime',
      'description' => '发布时间',
      'model' => '5',
      'type' => 'datetime',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    21 => 
    array (
      'id' => '21',
      'name' => 'contents',
      'description' => '视频内容',
      'model' => '5',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '500',
      'height' => '500',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '3',
      'editable' => '1',
    ),
    22 => 
    array (
      'id' => '22',
      'name' => 'ontop',
      'description' => '排序',
      'model' => '5',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '0',
      'order' => '4',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '18',
    1 => '19',
    2 => '20',
    3 => '21',
  ),
  'searchable' => 
  array (
    0 => '18',
    1 => '19',
    2 => '20',
    3 => '21',
  ),
);