document.writeln("<link type=\'text/css\' rel=\'stylesheet\' href=\'css/index.css\' />");
document.writeln("<div class=\'whole\'>");
document.writeln("			<div class=\'header\'><!--顶部-->");
document.writeln("				中间为搜索，右边为天气和日期、客服等<div class=\'logo\'>logo图标</div>	");
document.writeln("				<div class=\'search\'><!-- 搜索-->");
document.writeln("				  <nav class=\'header-search\'>");
document.writeln("				    <form  method=\'get\'>");
document.writeln("					  <button class=\'search-btn\'></button>");
document.writeln("					  <input class=\'search-field\' type=\'text\' onblur=\'if(this.value==\'\')this.value=\'Search\';\' onfocus=\'if(this.value==\'Search\')this.value=\'\';\' value=\'Search\'/>");
document.writeln("				    </form>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("				");
document.writeln("				<div id=\'main-navigation\'><!--导航-->");
document.writeln("					  <div class=\'container\'>");
document.writeln("				      <ul class=\'main-menu\'>");
document.writeln("					<li><a href=\'index.html\' id=\'current\'>首页</a>");
document.writeln("					");
document.writeln("					");
document.writeln("					<li><a href=\'chana_culture.html\'>陶瓷文化</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("					</ul>");
document.writeln("					</li>");
document.writeln("					");
document.writeln("					<li><a href=\'scenery_introduction.html\'> 景点介绍</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("					</ul>");
document.writeln("					</li>");
document.writeln("					");
document.writeln("					<li><a href=\'travel_strategy.html\'>旅游攻略</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("					</ul>");
document.writeln("					</li>");
document.writeln("						");
document.writeln("					");
document.writeln("					<li><a href=\'customize.html\'>私人订制</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>	");
document.writeln("					</ul>");
document.writeln("					</li>");
document.writeln("					");
document.writeln("					<li><a href=\'travel_notes.html\'> 游记</a>");
document.writeln("					<ul>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("						<li><a href=\'\'>待定</a></li>");
document.writeln("					</li>");
document.writeln("			   </div>");
document.writeln("			   ");
document.writeln("              <div class=\'login_zhuce\'><!--登录和注册-->");
document.writeln("              	<a href=\'login.html\'>登录</a>");
document.writeln("              	<a href=\'zhuce.html\'>注册</a>");
document.writeln("              </div>");
document.writeln("            </div>  ");
